department_app/views/__init__.py
# department_app/views/__init__.py
"""
This is the __init__.py file of views module.
Imports the departments_views and employees_views submodules
Registers the user blueprint.
Specifies the logic on / address
"""
# pylint: disable=cyclic-import
# third-party imports
from flask import Blueprint
from flask import render_template

user = Blueprint('user', __name__)

# local imports
# pylint: disable=wrong-import-position
# disable wrong import positions because the blueprint must be
# registered before the views are imported
from . import department_views
from . import employee_views


@user.route('/')
def homepage():
    """
    This function renders the homepage template on the / route
    :return: the rendered home.html template
    """
    return render_template('home.html', title='Welcome')

department_app/templates/base.html
<!-- department_app/templates/base.html -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{title}}</title>
        <!-- For responsive display -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Linking a custom stylesheet -->
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <!-- Linking jQuery, Bootstrap and tools for date widget -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
        <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
        <script src="{{ url_for('static', filename='create_table.js') }}"></script>
    <body>
        <header>
            <!-- A navigation bar -->
            <nav class="navbar navbar-expand-sm bg-light">
                <!-- Brand -->
                <a class="navbar-brand" href="{{ url_for('user.homepage') }}">The department app</a>
                <!-- Toggler/collapsibe Button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Navbar links -->
                <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ url_for('user.homepage') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user.show_departments') }}">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('user.show_employees') }}">Employees</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        {% block body %}
        {% endblock %}

        <!-- Some other needed links to Bootstrap and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    </body>
</html>

department_app/templates/home.html
<!-- department_app/templates/home.html -->
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<main>
    <!-- A main content -->
    <div class="container margin-home">
        <!-- A page heading -->
        <h1 class="text-center big-text">The department app</h1>
        <!-- A page description -->
        <p class="text-center margin-top description-width">This web service allows you to work with employees, their roles and departments and perform different operations to them.</p>
        <!-- A button to start work -->
        <div class="col text-center margin-top">
            <a href="{{ url_for('user.show_departments') }}" class="btn btn-primary" role="button">Start work</a>
        </div>
    </div>
</main>
{% endblock %}